# -*- coding: utf-8 -*-
"""edamodule 315.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16uLdiWycAX_t1YTsi6bzqHwRAlhmTabY
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

df = pd.read_csv("dirty_dataset.csv")
df.head()

df.isnull().sum()

df.describe()

df.info()

df['age'] = df['age'].fillna(df['age'].mean())
df['income'] = df['income'].fillna(df['income'].mean())
df['education'] = df['education'].fillna(df['education'].mode()[0])
df['marital_status'] = df['marital_status'].fillna(df['marital_status'].mode()[0])
df['loan_amount'] = df['loan_amount'].fillna(df['loan_amount'].mean())
df['avg_monthly_spend'] = df['avg_monthly_spend'].fillna(df['avg_monthly_spend'].mean())
df

df.isnull().sum()

sns.histplot(x = df['education'], kde = True)
plt.xlabel("education")
plt.ylabel("count")
plt.title("count of education")
plt.show()

sns.boxplot(x = df['age'], y = df['marital_status'])
plt.xlabel("age")
plt.ylabel("marital_status")
plt.title("age vs marital_status")
plt.show()

sns.scatterplot(x= df['age'], y = df['income'],  hue = df['education'])

sns.barplot(x= df['income'], y = df['age'])

sns.lineplot(x= df['avg_monthly_spend'],y =df['loan_amount'])

corr = df.corr(numeric_only = True)
sns.heatmap(corr, annot = True)

import plotly.express as px
fig = px.pie(df, values='age', names='income', title='Interactive EDA Pie')
fig.show()

